import paches from CDH3u0

diff --git a/bin/hadoop b/bin/hadoop
--- a/bin/hadoop
+++ b/bin/hadoop
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-
 # Licensed to the Apache Software Foundation (ASF) under one or more
 # contributor license agreements.  See the NOTICE file distributed with
 # this work for additional information regarding copyright ownership.
@@ -24,6 +23,12 @@
 #
 #   HADOOP_CLASSPATH Extra Java CLASSPATH entries.
 #
+#   HADOOP_USER_CLASSPATH_FIRST      When defined, the HADOOP_CLASSPATH is 
+#                                    added in the beginning of the global
+#                                    classpath. Can be defined, for example,
+#                                    by doing 
+#                                    export HADOOP_USER_CLASSPATH_FIRST=true
+#
 #   HADOOP_HEAPSIZE  The maximum amount of heap to use, in MB. 
 #                    Default is 1000.
 #
@@ -46,6 +51,8 @@ bin=`cd "$bin"; pwd`
 
 . "$bin"/hadoop-config.sh
 
+HADOOP_IDENT_STRING=${HADOOP_IDENT_STRING:-$USER}
+
 cygwin=false
 case "`uname`" in
 CYGWIN*) cygwin=true;;
@@ -64,6 +71,7 @@ if [ $# = 0 ]; then
   echo "  fsck                 run a DFS filesystem checking utility"
   echo "  fs                   run a generic filesystem user client"
   echo "  balancer             run a cluster balancing utility"
+  echo "  fetchdt              fetch a delegation token from the NameNode"
   echo "  jobtracker           run the MapReduce job Tracker node" 
   echo "  pipes                run a Pipes job"
   echo "  tasktracker          run a MapReduce task Tracker node" 
@@ -72,7 +80,10 @@ if [ $# = 0 ]; then
   echo "  version              print the version"
   echo "  jar <jar>            run a jar file"
   echo "  distcp <srcurl> <desturl> copy file or directories recursively"
-  echo "  archive -archiveName NAME <src>* <dest> create a hadoop archive"
+  echo "  archive -archiveName NAME -p <parent path> <src>* <dest> create a hadoop archive"
+  echo "  oiv                  apply the offline fsimage viewer to an fsimage"
+  echo "  classpath            prints the class path needed to get the"
+  echo "                       Hadoop jar and the required libraries"
   echo "  daemonlog            get/set the log level for each daemon"
   echo " or"
   echo "  CLASSNAME            run the class named CLASSNAME"
@@ -112,6 +123,9 @@ fi
 # CLASSPATH initially contains $HADOOP_CONF_DIR
 CLASSPATH="${HADOOP_CONF_DIR}"
 CLASSPATH=${CLASSPATH}:$JAVA_HOME/lib/tools.jar
+if [ "$HADOOP_USER_CLASSPATH_FIRST" != "" ] && [ "$HADOOP_CLASSPATH" != "" ] ; then
+  CLASSPATH=${CLASSPATH}:${HADOOP_CLASSPATH}
+fi
 
 # for developers, add Hadoop classes to CLASSPATH
 if [ -d "$HADOOP_HOME/build/classes" ]; then
@@ -134,7 +148,7 @@ IFS=
 if [ -d "$HADOOP_HOME/webapps" ]; then
   CLASSPATH=${CLASSPATH}:$HADOOP_HOME
 fi
-for f in $HADOOP_HOME/hadoop-*-core.jar; do
+for f in $HADOOP_HOME/hadoop-core-*.jar; do
   CLASSPATH=${CLASSPATH}:$f;
 done
 
@@ -153,15 +167,15 @@ for f in $HADOOP_HOME/lib/jsp-2.1/*.jar; do
   CLASSPATH=${CLASSPATH}:$f;
 done
 
-for f in $HADOOP_HOME/hadoop-*-tools.jar; do
+for f in $HADOOP_HOME/hadoop-tools-*.jar; do
   TOOL_PATH=${TOOL_PATH}:$f;
 done
-for f in $HADOOP_HOME/build/hadoop-*-tools.jar; do
+for f in $HADOOP_HOME/build/hadoop-tools-*.jar; do
   TOOL_PATH=${TOOL_PATH}:$f;
 done
 
 # add user-specified CLASSPATH last
-if [ "$HADOOP_CLASSPATH" != "" ]; then
+if [ "$HADOOP_USER_CLASSPATH_FIRST" = "" ] && [ "$HADOOP_CLASSPATH" != "" ]; then
   CLASSPATH=${CLASSPATH}:${HADOOP_CLASSPATH}
 fi
 
@@ -182,7 +196,13 @@ fi
 unset IFS
 
 # figure out which class to run
-if [ "$COMMAND" = "namenode" ] ; then
+if [ "$COMMAND" = "classpath" ] ; then
+  if $cygwin; then
+    CLASSPATH=`cygpath -p -w "$CLASSPATH"`
+  fi
+  echo $CLASSPATH
+  exit
+elif [ "$COMMAND" = "namenode" ] ; then
   CLASS='org.apache.hadoop.hdfs.server.namenode.NameNode'
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_NAMENODE_OPTS"
 elif [ "$COMMAND" = "secondarynamenode" ] ; then
@@ -209,6 +229,8 @@ elif [ "$COMMAND" = "fsck" ] ; then
 elif [ "$COMMAND" = "balancer" ] ; then
   CLASS=org.apache.hadoop.hdfs.server.balancer.Balancer
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_BALANCER_OPTS"
+elif [ "$COMMAND" = "fetchdt" ] ; then
+  CLASS=org.apache.hadoop.hdfs.tools.DelegationTokenFetcher
 elif [ "$COMMAND" = "jobtracker" ] ; then
   CLASS=org.apache.hadoop.mapred.JobTracker
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_JOBTRACKER_OPTS"
@@ -217,8 +239,10 @@ elif [ "$COMMAND" = "tasktracker" ] ; then
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_TASKTRACKER_OPTS"
 elif [ "$COMMAND" = "job" ] ; then
   CLASS=org.apache.hadoop.mapred.JobClient
+  HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
 elif [ "$COMMAND" = "queue" ] ; then
   CLASS=org.apache.hadoop.mapred.JobQueueClient
+  HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
 elif [ "$COMMAND" = "pipes" ] ; then
   CLASS=org.apache.hadoop.mapred.pipes.Submitter
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
@@ -227,6 +251,7 @@ elif [ "$COMMAND" = "version" ] ; then
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
 elif [ "$COMMAND" = "jar" ] ; then
   CLASS=org.apache.hadoop.util.RunJar
+  HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
 elif [ "$COMMAND" = "distcp" ] ; then
   CLASS=org.apache.hadoop.tools.DistCp
   CLASSPATH=${CLASSPATH}:${TOOL_PATH}
@@ -236,6 +261,10 @@ elif [ "$COMMAND" = "daemonlog" ] ; then
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
 elif [ "$COMMAND" = "archive" ] ; then
   CLASS=org.apache.hadoop.tools.HadoopArchives
+  CLASSPATH=${CLASSPATH}:${TOOL_PATH}
+  HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
+elif [ "$COMMAND" = "oiv" ] ; then
+  CLASS=org.apache.hadoop.hdfs.tools.offlineImageViewer.OfflineImageViewer
   CLASSPATH=${CLASSPATH}:${TOOL_PATH}
   HADOOP_OPTS="$HADOOP_OPTS $HADOOP_CLIENT_OPTS"
 elif [ "$COMMAND" = "sampler" ] ; then
@@ -251,14 +280,19 @@ if $cygwin; then
   HADOOP_HOME=`cygpath -w "$HADOOP_HOME"`
   HADOOP_LOG_DIR=`cygpath -w "$HADOOP_LOG_DIR"`
   TOOL_PATH=`cygpath -p -w "$TOOL_PATH"`
+  JAVA_LIBRARY_PATH=`cygpath -p -w "$JAVA_LIBRARY_PATH"`
 fi
+
 # setup 'java.library.path' for native-hadoop code if necessary
-JAVA_LIBRARY_PATH=''
-if [ -d "${HADOOP_HOME}/build/native" -o -d "${HADOOP_HOME}/lib/native" ]; then
-  JAVA_PLATFORM=`CLASSPATH=${CLASSPATH} ${JAVA} -Xmx32m org.apache.hadoop.util.PlatformName | sed -e "s/ /_/g"`
+if [ -d "${HADOOP_HOME}/build/native" -o -d "${HADOOP_HOME}/lib/native" -o -d "${HADOOP_HOME}/sbin" ]; then
+  JAVA_PLATFORM=`CLASSPATH=${CLASSPATH} ${JAVA} -Xmx32m ${HADOOP_JAVA_PLATFORM_OPTS} org.apache.hadoop.util.PlatformName | sed -e "s/ /_/g"`
   
   if [ -d "$HADOOP_HOME/build/native" ]; then
-    JAVA_LIBRARY_PATH=${HADOOP_HOME}/build/native/${JAVA_PLATFORM}/lib
+    if [ "x$JAVA_LIBRARY_PATH" != "x" ]; then
+        JAVA_LIBRARY_PATH=${JAVA_LIBRARY_PATH}:${HADOOP_HOME}/build/native/${JAVA_PLATFORM}/lib
+    else
+        JAVA_LIBRARY_PATH=${HADOOP_HOME}/build/native/${JAVA_PLATFORM}/lib
+    fi
   fi
   
   if [ -d "${HADOOP_HOME}/lib/native" ]; then
@@ -268,6 +302,8 @@ if [ -d "${HADOOP_HOME}/build/native" -o -d "${HADOOP_HOME}/lib/native" ]; then
       JAVA_LIBRARY_PATH=${HADOOP_HOME}/lib/native/${JAVA_PLATFORM}
     fi
   fi
+
+  _JSVC_PATH=${HADOOP_HOME}/sbin/${JAVA_PLATFORM}/jsvc
 fi
 
 # cygwin path translation
@@ -285,5 +321,136 @@ if [ "x$JAVA_LIBRARY_PATH" != "x" ]; then
 fi  
 HADOOP_OPTS="$HADOOP_OPTS -Dhadoop.policy.file=$HADOOP_POLICYFILE"
 
-# run it
-exec "$JAVA" $JAVA_HEAP_MAX $HADOOP_OPTS -classpath "$CLASSPATH" $CLASS "$@"
+
+###########################################################################
+# DAEMON SETTINGS
+###########################################################################
+# For any command that ends in 'node', we are starting one of the daemons.
+# In this case, we do some special processing in order to automatically
+# setuid to the correct user.
+#
+# The user itself is determined as one of the following, in descending
+# precedence:
+#  HADOOP_<node>NODE_USER variable
+#  the current userid, so long as that userid is not root
+#
+# After the above is determined, it is stored into the local variable
+# _HADOOP_DAEMON_USER
+#
+# We also need to determine the "run mode". This can be one of the following:
+#
+#  "jsvc" - only supported for the datanode - we use the jsvc wrapper in
+#           the sbin/<platform> directory in order to setuid to the target
+#           user. Requires that this script is running as root.
+#  "su" -   supported only when running as root and /bin/su exists.
+#           Uses su in order to assume the identity of the daemon user.
+#  "normal" - supported only when already running as the target user.
+###########################################################################
+if [[ "$COMMAND" == *node ]] || [[ "$COMMAND" == *tracker ]]; then
+  command_uc=$(echo $COMMAND| tr a-z A-Z)
+  user_var="HADOOP_${command_uc}_USER"
+  _HADOOP_DAEMON_USER=$(eval "echo \$$user_var")
+  _HADOOP_DAEMON_USER=${_HADOOP_DAEMON_USER:-$(id -un)}
+
+  if [ -z "$_HADOOP_DAEMON_USER" ]; then
+    echo Please specify a user to run the $COMMAND by setting $user_var
+    exit 1
+  elif  [ "$_HADOOP_DAEMON_USER" == "root" ]; then
+    echo May not run daemons as root. Please specify $user_var
+    exit 1
+  fi
+
+  if [ "$EUID" = "0" ] ; then
+    if [ "$COMMAND" == "datanode" ] && [ -x "$_JSVC_PATH" ]; then
+      _HADOOP_RUN_MODE="jsvc"
+    elif [ -x /bin/su ]; then
+      _HADOOP_RUN_MODE="su"
+    else
+      echo "Daemon wants to run as $_HADOOP_DAEMON_USER but script is running as root"
+      echo "and su is not available."
+      exit 1
+    fi
+  else
+    # We must be running as the user we want to run as, if we can't use jsvc or su
+    # to drop privileges
+    if [ "$_HADOOP_DAEMON_USER" != "$(whoami)" ]; then
+      echo Daemon wants to run as $_HADOOP_DAEMON_USER but not running as that user or root.
+      exit 1
+    fi
+    _HADOOP_RUN_MODE="normal"
+  fi
+else
+  # Normal client command
+  _HADOOP_RUN_MODE="normal"
+fi
+
+###########################################################################
+# Actually run the JVM
+###########################################################################
+case "$_HADOOP_RUN_MODE" in
+  jsvc)
+    case "$COMMAND" in
+      datanode)
+        _JSVC_STARTER_CLASS=org.apache.hadoop.hdfs.server.datanode.SecureDataNodeStarter
+      ;;
+      *)
+        echo "Cannot start $COMMAND with jsvc"
+        exit 1
+      ;;
+    esac
+
+    if [ "$_HADOOP_DAEMON_DETACHED" = "true" ]; then
+      _JSVC_FLAGS="-pidfile $_HADOOP_DAEMON_PIDFILE
+                  -errfile &1
+                  -outfile $_HADOOP_DAEMON_OUT"
+    else
+      # Even though we are trying to run a non-detached datanode,
+      # jsvc will not write to stdout/stderr, so we have to pipe
+      # it and tail the logfile.
+      log_path=/tmp/jsvc_${COMMAND}.$$
+      _JSVC_FLAGS="-nodetach
+                   -errfile &1
+                   -outfile $log_path"
+      echo Non-detached jsvc output piping to: $log_path
+      touch $log_path
+      tail -f $log_path &
+    fi
+    unset _HADOOP_DAEMON_DETACHED
+
+    exec "$_JSVC_PATH" -Dproc_$COMMAND \
+                       $_JSVC_FLAGS \
+                       -user "$_HADOOP_DAEMON_USER" \
+                       -cp "$CLASSPATH" \
+                       $JAVA_HEAP_MAX $HADOOP_OPTS \
+                       $_JSVC_STARTER_CLASS "$@"
+  ;;
+
+  normal | su)
+    # If we need to su, tack the command into a local variable
+    if [ $_HADOOP_RUN_MODE = "su" ]; then
+      _JAVA_EXEC="su $_HADOOP_DAEMON_USER -s $JAVA --"
+    else
+      _JAVA_EXEC="$JAVA"
+    fi
+
+    if [ "$_HADOOP_DAEMON_DETACHED" = "true" ]; then
+      unset _HADOOP_DAEMON_DETACHED
+      touch $_HADOOP_DAEMON_OUT
+      nohup $_JAVA_EXEC -Dproc_$COMMAND $JAVA_HEAP_MAX $HADOOP_OPTS -classpath "$CLASSPATH" $CLASS "$@" > "$_HADOOP_DAEMON_OUT" 2>&1 < /dev/null &
+      if [ "$EUID" == "0" ]; then
+        chown $_HADOOP_DAEMON_USER $_HADOOP_DAEMON_OUT
+      fi
+      echo $! > "$_HADOOP_DAEMON_PIDFILE"
+      sleep 1
+      head "$_HADOOP_DAEMON_OUT"
+    else
+      # For normal operation, just run the command
+      exec $_JAVA_EXEC -Dproc_$COMMAND $JAVA_HEAP_MAX $HADOOP_OPTS -classpath "$CLASSPATH" $CLASS "$@"
+    fi
+  ;;
+
+  *)
+    echo Bad run mode: $_HADOOP_RUN_MODE
+    exit 1
+  ;;
+esac
